### ISSUE TITLE
Python version and requirements

### ISSUE THREAD

**Issue by mcprocaccini** [NickDrake117/GNNkeras#5]
Hi, I've just downloaded your code and tested it. 
I've noticed that I need python3.9 version or higher for running the code correctly. 
It would be good if you can add a note in the README about, or write a version check into the setup.py script. 

like this: 

import sys

if sys.version_info < (3,9):
    print('Please upgrade your Python version to 3.9.x')
    print('Current version: ',sys.version)
    sys.exit()

Also, there is another package required: scipy. You may add it into the requirements.txt

**Comment by NickDrake117** [comment]
Thank you for your suggestions. Just added to the requirements.txt :-)
I'm working to improve the repo, in a a few days I'll be able to make a pull request on main brach. I suggest yo downloading that version, as many memory/speed improvements arr made ;-)
